# Generated by Django 4.1 on 2023-01-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('deleted_time', models.DateTimeField(editable=False, null=True, verbose_name='deleted time')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='deleted')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='username')),
                ('wallet_amount', models.FloatField(verbose_name='wallet_amount')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('deleted_time', models.DateTimeField(editable=False, null=True, verbose_name='deleted time')),
                ('deleted', models.BooleanField(default=False, editable=False, verbose_name='deleted')),
                ('crypto_name', models.CharField(choices=[('ABAN', 'Aban'), ('BTC', 'Bitcoin')], max_length=10, verbose_name='sum_label')),
                ('crypto_volume', models.FloatField(verbose_name='crypto_volume')),
                ('is_bought', models.BooleanField(default=False, verbose_name='is_bought')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='order.userprofile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
